export const UsersActionTypes = {
    START_USERS_LOADING: 'START_USERS_LOADING',
    END_USERS_LOADING: 'END_USERS_LOADING',
    SET_USERS_ERROR: 'SET_USERS_ERROR',
    CLEAR_USERS_ERROR: 'CLEAR_USERS_ERROR',
    SET_USERS: 'SET_USERS',
    CLEAR_USERS: 'CLEAR_USERS',
}